import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create WB3 MODAL EXAMPLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="sc-jSgupP fvekwG sc-jJEJSO laquCT">
        <div class="sc-eCssSg dWCXGH sc-gWHgXt ikxKmn">
          <h3>Test Web3Modal example</h3>

          <div class="sc-giIncl gHUUHu">
            <button type="button" class="sc-kLgntA mqBxb">
              <div class="sc-ezrdKe bAYFRD"></div>
          <div class="sc-bYEvPH khGBIg">
        </div>Connect</button>
      </div>

      <div class="sc-giIncl gHUUHu">
            <button type="button" class="sc-kLgntA mqBxb">
              <div class="sc-ezrdKe bAYFRD"></div>
          <div class="sc-bYEvPH khGBIg">
        </div>Desconnect</button>
      </div>
      </div>
      </div>

      <footer className={styles.footer}>
       
          Powered by {' MS-HACK '}
          <span className={styles.logo}>
          </span>
        
      </footer>
    </div>
  )
}
