import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create WB3 MODAL EXAMPLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="sc-jSgupP fvekwG sc-jJEJSO laquCT">
        <div class="sc-eCssSg dWCXGH sc-gWHgXt ikxKmn">
          <h3>Test Web3Modal example</h3>

          <div class="sc-giIncl gHUUHu">
            <button type="button" class="sc-kLgntA mqBxb">
              <div class="sc-ezrdKe bAYFRD"></div>
          <div class="sc-bYEvPH khGBIg">
        </div>Connect</button>
      </div>

      <div class="sc-giIncl gHUUHu">
            <button type="button" class="sc-kLgntA mqBxb">
              <div class="sc-ezrdKe bAYFRD"></div>
          <div class="sc-bYEvPH khGBIg">
        </div>desconnect</button>
      </div>

      <div id="network">
              <p>
                <strong>Connected blockchain:</strong> <span id="network-name"></span>
              </p>

              <p>
                <strong>Selected account:</strong> <span id="selected-account"></span>
              </p>

            </div>



         

            <h3>All account balances</h3>

            <table class="table table-listing">
              <thead>
                <th>Address</th>
                <th>ETH balance</th>
              </thead>

              <tbody id="accounts">
              </tbody>
            </table>

            <p>Please try to switch between different accounts in your wallet if your wallet supports this functonality.</p>
            

      </div>
      </div>

      <footer className={styles.footer}>
       
          Powered by {' MS-HACK '}
          <span className={styles.logo}>
          </span>
        
      </footer>
    </div>
  )
}
